### ISSUE TITLE
`adapter._fixId` error after iobroker upgrade

### ISSUE THREAD

**Issue by mobilutz** [ioBroker/ioBroker.node-red#270]
After updating iobroker js-controller to 4.0.4 I get the following error for iobroker.node-red:
```
7 Feb 20:11:43 - TypeError: adapter._fixId is not a function at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.node-red/nodes/ioBroker.js:132:96) at processImmediate (internal/timers.js:466:21)
```

I am running iobroker.node-red in the following version: 2.4.1

NodeJs: 14.19.0
NPM: 6.14.16

The adapter just keeps restarting 😦

**Comment by Apollon77** [comment]
will be fixed in 2.4.2 in some minutes

**Comment by mobilutz** [comment]
Thanks @Apollon77
The adapter is working again!
